# App-level deploy configuration for SIT environment

rtf.applicationName=my-mule-app
rtf.replicas=2
rtf.cpuReserved=500m
rtf.cpuMax=1000m
rtf.memoryReserved=700Mi
rtf.memoryMax=1000Mi
rtf.provider=MC
mule.env=sit
skipTests=true
