# Use postgres/example user/password credentials
version: '3.8'

services:
  postgres:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=od
      - POSTGRES_PASSWORD=od
      - POSTGRES_DB=mydb
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: odoraf@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoraf
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: